import type { Metadata } from "next";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster";

import { ThemeProvider } from "@/components/theme-provider"
import { DARK_LOGO } from "@/constants/logos";

import { EdgeStoreProvider } from "@/lib/edgestore";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Sneaker Deals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
            <link rel="icon" href={DARK_LOGO} />
        </head>
        <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
          )}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <EdgeStoreProvider>
                {children}
                <Toaster/>
              </EdgeStoreProvider>
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
